advanced_blueprint.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, jsonify
from flask_sqlalchemy import SQLAlchemy

advanced_blueprint = Blueprint('advanced_blueprint', __name__, template_folder='templates')
from flight_blueprint import Flight


@advanced_blueprint.route('/advanced.html', methods=['GET'])
def advanced_flight_form():
    return render_template('Website/advanced.html')

@advanced_blueprint.route('/advanced.html', methods=['POST'])
def advanced_flight():
    start_date = request.form['start_date']
    end_date = request.form['end_date']
    
    try:
        # Query flights within the specified period
        print("Trying to query flights...")
        flights = Flight.query.filter(Flight.departureDate.between(start_date, end_date)).all()
        print("Number of flights found:", len(flights))
        return render_template('Website/advanced.html', flights=flights)
    except Exception as e:
        error_info = "An error occurred while processing your request."
        return render_template('Website/advanced.html', error_info=e)

employee_blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for
from sqlalchemy.exc import IntegrityError

employees_blueprint = Blueprint('employee_blueprint', __name__, template_folder='templates')
from app import db

class Employee(db.Model):
    __tablename__ = 'Employee'
    idEmployee = db.Column(db.Integer, primary_key=True, unique=True)
    firstName = db.Column(db.String(45))
    lastName = db.Column(db.String(45))
    positionID = db.Column(db.Integer)
    salary = db.Column(db.Integer)
    status = db.Column(db.Enum('Active', 'Retired', 'Vacationing', 'Fired'))

#Add Employee
@employees_blueprint.route('/add_employee.html', methods=['GET'])
def add_employee_form():
    return render_template('/Website/add_employee.html')

@employees_blueprint.route('/add_employee.html', methods=['POST'])
def add_employee():
    idEmployee = request.form['idEmployee']
    firstName = request.form['FirstName']
    lastName = request.form['LastName']
    positionID = request.form['positionID']
    salary = request.form['Salary']
    status = request.form['Status']

    new_employee = Employee(idEmployee=idEmployee, firstName=firstName, lastName=lastName, positionID=positionID, salary=salary, status=status)

    db.session.add(new_employee)
    try:
        db.session.commit()
        return render_template('Website/success.html', title = "Employee Added", employee=new_employee)
    except IntegrityError as e:
        db.session.rollback()
        error_info = str(e.orig)
        return render_template('Website/error.html', error_info=error_info)
    except Exception as e:
        db.session.rollback()
        error_info = "An error occurred while processing your request."
        return render_template('Website/error.html', error_info=e)
    finally:
        pass

#Search Employee
@employees_blueprint.route('/search_employee.html')
def searchEmployee():
    return render_template('Website/search_employee.html')

@employees_blueprint.route('/search_employee.html', methods=['POST'])
def search_employee():
    idEmployee = request.form['employeeID']

    try:
        employee = Employee.query.filter(Employee.idEmployee==idEmployee).first()
        return render_template('Website/success.html', title = "Employee Found", employee=employee)
    except Exception as e:
        error_info = "An error occurred while processing your request."
        return render_template('Website/error.html', error_info=e)


#update Employee
@employees_blueprint.route('/update_employee.html', methods=['POST'])
def update_employee():
    idEmployee = request.form['idEmployee']

    try:
        employee = Employee.query.filter(Employee.idEmployee==idEmployee).first()
        if 'New-FirstName' in request.form and request.form['New-FirstName'] != "":
            employee.firstName = request.form['New-FirstName']
        if 'New-LastName' in request.form and request.form['New-LastName'] != "":
            employee.lastName = request.form['New-LastName']
        if 'New-positionID' in request.form and request.form['New-positionID'] != "":
            employee.positionID = request.form['New-positionID']
        if 'New-Salary' in request.form and request.form['New-Salary'] != "":
            employee.salary = request.form['New-Salary']
        if 'New-Status' in request.form and request.form['New-Status'] != "":
            employee.status = request.form['New-Status']
        db.session.commit()

        employee = Employee.query.filter(Employee.idEmployee==idEmployee).first()
        return render_template('Website/success.html', title= "Employee Updated", employee=employee)
    except Exception as e:
        error_info = "An error occurred while processing your request."
        return render_template('Website/error.html', error_info=e)
    

#delete Employee
@employees_blueprint.route('/delete_employee.html', methods=['POST'])
def delete_employee():
    idEmployee = request.form['idEmployee']

    try:
        employee = Employee.query.filter(Employee.idEmployee==idEmployee).first()
        employee.status = "Fired"
        db.session.commit()
        return render_template('Website/success.html', title="Employee Fired", employee=employee)
    except Exception as e:
        error_info = "An error occurred while processing your request."
        return render_template('Website/error.html', error_info=e)

templates/Website/add_employee.html
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <title>Employment Addition</title>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
  </head>

    <body class="home">
      <header class="header">
        <a href="#" class="logo">Airline DBMS</a>
        <nav class="navbar">
            <a href="add_employee.html"> Employee</a>
            <a href="search_employee.html">Search Employee</a>
            <a href="schedule_flight.html">Flight Scheduler</a>
            <a href="create_department.html">Create Department</a>
            <a href="add_plane.html">Add Plane</a>
            <a href="advanced.html">Advanced</a>
        </nav>
      </header>
<div class="all-forms">
    <div class="add-form">
      <div class="search-title"> Add Employee</div>
        <form method="post" action="{{ url_for('employee_blueprint.add_employee') }}">
          <div class="input-box">
            <label for="idEmployee">Employee ID:</label>
            <input type="text" placeholder="Enter EMP ID" name ="idEmployee" required>
          </div>

          <div class="input-box">
            <label for="FirstName">First Name</span>
            <input type="text" placeholder="Enter First Name" name= "FirstName" required>
          </div>

          <div class="input-box">
            <label for ="LastName">Last Name</span>
            <input type="text" placeholder="Enter Last Name" name = "LastName" required>
          </div>

          <div class="input-box">
            <label for="positionID">Position ID</span>
            <input type="text" placeholder="Enter Position ID" name = "positionID" required>
          </div>

          <div class="input-box">
            <label for="Salary">Salary:</label>
            <input type="text" placeholder="Enter Salary" required name = "Salary">
          </div>

          <div class="input-box">
            <label for="Status">Employment Status:</label>
            <select name="Status" required>
                <option value="Active">Active</option>
                <option value="Retired">Retired</option>
                <option value="Vacationing">Vacationing</option>
                <option value="Fired">Fired</option>
            </select><br>
          </div>

          <div class = "input-box">
            <input type="submit" value="Add Employee">
          </div>
      </form>
    </div>

    <div class="update-form">
      <div class="dep-title"> Update Employee</div>
        <form method="post" action="{{ url_for('employee_blueprint.add_employee') }}">
          <div class="input-box">
            <label for="idEmployee">Employee ID:</label>
            <input type="text" placeholder="Enter EMP ID" name ="idEmployee" required>
          </div>

          <div class="input-box">
            <label for="FirstName">New First Name</span>
            <input type="text" placeholder="Enter New First Name" name= "New-FirstName" required>
        </div>

        <div class="input-box">
            <label for ="LastName">New Last Name</span>
            <input type="text" placeholder="Enter New Last Name" name = "New-LastName" required>
        </div>

          <div class="input-box">
            <label for="positionID">New Position ID</span>
            <input type="text" placeholder="Enter New Position ID" name = "New-positionID" required>
        </div>

          <div class="input-box">
            <label for="Salary">New Salary:</label>
            <input type="text" placeholder="Enter New Salary" required name = "New-Salary">
          </div>

          <div class="input-box">
            <label for="Status">New Employment Status:</label>
            <select name="Status" required>
                <option value="Active">Active</option>
                <option value="Retired">Retired</option>
                <option value="Vacationing">Vacationing</option>
                <option value="Fired">Fired</option>
            </select><br>
          </div>

          <div class = "input-box">
            <input type="submit" value="Update Employee">
          </div>
      </form>
    </div>

    <div class="delete-form">
      <div class="dep-title"> Delete Employee</div>
        <form method="post" action="{{ url_for('employee_blueprint.add_employee') }}">
          <div class="input-box">
            <label for="idEmployee">Employee ID:</label>
            <input type="text" placeholder="Enter EMP ID" name ="idEmployee" required>
          </div>

          <div class = "input-box">
            <input type="submit" value="Delete">
          </div>
      </form>
    </div>
  </div>



    

    
    
    
  </body>
</html>

templates/Website/add_plane.html
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <title>Login Form</title>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
  </head>

    <body class="home">
      <header class="header">
        <a href="#" class="logo">Airline DBMS</a>
        <nav class="navbar">
            <a href="add_employee.html">Add Employee</a>
            <a href="search_employee.html">Search Employee</a>
            <a href="schedule_flight.html">Flight Scheduler</a>
            <a href="create_department.html">Create Department</a>
            <a href="add_plane.html">Add Plane</a>
            <a href="advanced.html">Advanced</a>
        </nav>
      </header>

<div class="all-forms">
      
  <div class="add-form">
    <div class="search-title">Add Plane</div>
      <form method="post" action="{{ url_for('plane_blueprint.add_plane') }}">
        <div class="input-box">
          <label for="idPlane" >Plane ID:</label>
          <input type="text" name="idPlane" placeholder="Enter Plane ID" required><br>
        </div>

        <div class="input-box">
          <label for="capacity">Capacity:</label>
          <input type="number" name="capacity" placeholder="Enter Plane Capacity" required><br>
        </div>

        <div class="input-box">
          <label for="crewID">Crew ID:</label>
          <input type="number" name="crewID" placeholder="Enter Crew ID" required><br>
        </div>

        <div class="input-box">
          <label for="planeType">Plane Type:</label>
          <select name="planeType" required>
              <option value="Private">Private</option>
              <option value="Commercial">Commercial</option>
              <option value="Jumbo">Jumbo</option>
              <option value="Cargo">Cargo</option>
          </select><br>
        </div>

        <div class = "input-box">
          <input type="submit" value="Add Plane">
        </div>
    </form>
  </div>

  <div class="add-form">
    <div class="dep-title">Update Add Plane</div>
      <form method="post" action="{{ url_for('plane_blueprint.add_plane') }}">
        <div class="input-box">
          <label for="idPlane" >Plane ID:</label>
          <input type="text" name="idPlane" placeholder="Enter Plane ID" required><br>
        </div>

        <div class="input-box">
          <label for="capacity">New Capacity:</label>
          <input type="number" name="capacity" placeholder="Enter New Capacity" required><br>
        </div>

        <div class="input-box">
          <label for="crewID">New Crew ID:</label>
          <input type="number" name="crewID" placeholder="Enter New Crew ID" required><br>
        </div>

        <div class="input-box">
          <label for="planeType">New Plane Type:</label>
          <select name="planeType" required>
              <option value="Private">Private</option>
              <option value="Commercial">Commercial</option>
              <option value="Jumbo">Jumbo</option>
              <option value="Cargo">Cargo</option>
          </select><br>
        </div>

        <div class = "input-box">
          <input type="submit" value="Update Plane">
        </div>
    </form>
  </div>

  <div class="add-form">
    <div class="dep-title">Delete Add Plane</div>
      <form method="post" action="{{ url_for('plane_blueprint.add_plane') }}">
        <div class="input-box">
          <label for="idPlane" >Plane ID:</label>
          <input type="text" name="idPlane" placeholder="Enter New Plane ID" required><br>
        </div>

        <div class = "input-box">
          <input type="submit" value="Delete Plane">
        </div>
    </form>
  </div>

</div>

  </body>
</html>

templates/Website/advanced.html
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Advanced Functionality</title>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
</head>

    <body class="home">
        <header class="header">
            <a href="#" class="logo">Airline DBMS</a>
            <nav class="navbar">
                <a href="add_employee.html">Add Employee</a>
                <a href="search_employee.html">Search Employee</a>
                <a href="schedule_flight.html">Flight Scheduler</a>
                <a href="create_department.html">Create Department</a>
                <a href="add_plane.html">Add Plane</a>
                <a href="advanced.html">Advanced</a>
            </nav>
        </header>

        <div class="add-form">
            <h1 class="search-title">Airport Query</h1>
            <form action="{{ url_for('advanced_blueprint.advanced_flight') }}" method="post">
                <div class="input-box">
                    <div class="inRow">
                        <input type="date" name="start_date" id="start_date" placeholder="Enter Start Date">
                    </div>
                    <div class="inRow">
                        <input type="date" name="end_date" id="end_date" placeholder="Enter End Date">
                    </div>
                </div>
                <div class="button">
                    <input type="submit" value="Submit">
                </div>
            </form>

            <h1>Viewing Window</h1>
            <div id="viewing-window">
                <h2>Flights</h2>
                <ul>
                    {% if flights %}
                        {% for flight in flights %}
                            <li class = "flight">
                                Destination: {{ flight.destination }}<br>
                                Departure Date: {{ flight.departureDate }}<br>
                                Departure Time: {{ flight.departureTime }}<br>
                                Flight Time: {{ flight.flightTime }} hours<br>
                            </li>
                        {% endfor %}
                    {% else %}
                        <p>No flights found for the specified period.</p>
                    {% endif %}
                </ul>
            </div>
        
        </div>

        

    </body>
</html>

templates/Website/create_department.html
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <title>Department Creation</title>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
  </head>

    <body class="home">
      <header class="header">
        <a href="#" class="logo">Airline DBMS</a>
        <nav class="navbar">
            <a href="add_employee.html">Add Employee</a>
            <a href="search_employee.html">Search Employee</a>
            <a href="schedule_flight.html">Flight Scheduler</a>
            <a href="create_department.html">Create Department</a>
            <a href="add_plane.html">Add Plane</a>
            <a href="advanced.html">Advanced</a>
        </nav>
      </header>


<div class="all-forms">
  <div class="add-form">
    <h1 class="search-title">Create Department</h1>
    <form method="post" action="{{ url_for('department_blueprint.add_department') }}">
        <div>
            <div class="input-box">
                <span class="details">Department ID</span>
                <input type="number" name = "idDepartment" placeholder="Enter Department ID" required>
            </div>

            <div class="input-box">
                <span class="details">Position Name</span>
                <input type="text" placeholder="Enter Position Name" required name = "positionName">
            </div>

            <div class="input-box">
              <label for="planeType">Classification</label>
              <select name="classification" required>
                  <option value="Air Crew">Air Crew</option>
                  <option value="Janitorial">Janitorial</option>
                  <option value="Concessions">Concessions</option>
                  <option value="Management">Management</option>
              </select><br>
            </div>

            <div class="input-box">
                <span class="details">Primary Location</span>
                <input type="text" name = "primaryLocation" placeholder="Enter Primary Location" required>
            </div>
        </div>
        <div class="button">
            <input type="Submit" value="Submit">
        </div>
    </form>
  </div>
  <div class="add-form">
    <div class="dep-title">Update Department</div>
    <form method="post" action="{{ url_for('department_blueprint.add_department') }}">
        <div class="user-details">
            <div class="input-box">
                <span class="details">Department ID</span>
                <input type="number" name = "idDepartment" placeholder="Enter Department ID" required>
            </div>

            <div class="input-box">
                <span class="details">New Pos. Name</span>
                <input type="text" placeholder="Enter Position Name" required name = "positionName">
            </div>

            <div class="input-box">
              <label for="planeType">New Classification</label>
              <select name="classification" required>
                  <option value="Air Crew">Air Crew</option>
                  <option value="Janitorial">Janitorial</option>
                  <option value="Concessions">Concessions</option>
                  <option value="Management">Management</option>
              </select><br>
            </div>

            <div class="input-box">
                <span class="details">New Primary Location</span>
                <input type="text" name = "primaryLocation" placeholder="Enter Primary Location" required>
            </div>
        </div>
        <div class="button">
            <input type="Submit" value="Update">
        </div>
    </form>
  </div>
  <div class="add-form">
    <div class="dep-title">Delete Department</div>
    <form method="post" action="{{ url_for('department_blueprint.add_department') }}">
        <div class="user-details">
            <div class="input-box">
                <span class="details">Department ID</span>
                <input type="number" name = "idDepartment" placeholder="Enter Department ID" required>
            </div>

        <div class="button">
            <input type="Submit" value="Delete">
        </div>
    </form>
  </div>
  
</div>

  </body>
</html>

templates/Website/error.html
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
  </head>

    <body class="home">
      <header class="header">
        <a href="#" class="logo">Airline DBMS</a>
        <nav class="navbar">
            <a href="add_employee.html">Add Employee</a>
            <a href="search_employee.html">Search Employee</a>
            <a href="schedule_flight.html">Flight Scheduler</a>
            <a href="create_department.html">Create Department</a>
            <a href="add_plane.html">Add Plane</a>
            <a href="advanced.html">Advanced</a>
        </nav>
      </header>

      <div class="error-form">
        <div class>Error</div>
            <div class = search-title>{{ error_info }}</title>
      </div>

  </body>
</html>

templates/Website/login.html
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <title>Login Form</title>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
  </head>
  <body>
    <div class="container">
      <div class="form-box">
        <h1>Login</h1>
        <form class="login-form" onsubmit="redirectToPage()">
          <div class="form-content">
            <label for="First Name">First Name:</label>
            <input type="text" id="first" name="first" required />
          </div>

          <div class="form-content">
            <label for="Last Name">Last Name:</label>
            <input type="text" id="last" name="last" required />
          </div>

          <div class="form-content">
            <label for="empID">EmpID:</label>
            <input type="empID" id="empID" name="empID" required />
          </div>

          <div class="form-content">
            <button type="submit">Enter</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

templates/Website/schedule_flight.html
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <title>Flight Schedule</title>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
  </head>

    <body class="home">
      <header class="header">
        <a href="#" class="logo">Airline DBMS</a>
        <nav class="navbar">
            <a href="add_employee.html">Add Employee</a>
            <a href="search_employee.html">Search Employee</a>
            <a href="schedule_flight.html">Flight Scheduler</a>
            <a href="create_department.html">Create Department</a>
            <a href="add_plane.html">Add Plane</a>
            <a href="advanced.html">Advanced</a>
        </nav>
      </header>
<div class="all-forms">
  <div class="add-form">
    <div class="search-title">Schedule Flight</div>
    <form method="post" action="{{ url_for('flight_blueprint.schedule_flight') }}">
        <div>
            <div class="input-box">
                <span class="details">Flight Number</span>
                <input type="text" name = "idFlight" placeholder="Enter Flight Number" required>
            </div>
            <div class="input-box">
                <span class="details">Destination</span>
                <input type="text" name = "destination" placeholder="Enter Destination" required>
            </div>
            <div class="input-box">
                <span class="details">Plane ID</span>
                <input type="text" name = "planeID" placeholder="Enter Plane ID" required>
            </div>
            <div class="input-box">
                <span class="details">Departure Date</span>
                <input type="date" name = "departureDate" placeholder="Enter Departure Date" required>
            </div>
            <div class="input-box">
                <span class="details">Departure Time</span>
                <input type="time" name = "departureTime" placeholder="Enter Departure Time" required>
            </div>
            <div class="input-box">
                <span class="details">Flight Duration</span>
                <input type="number" name = "FlightTime"placeholder="Flight Duration in minutes" required>
            </div>
        </div>
        <div class="button">
            <input type="Submit" value="Submit">
        </div>
    </form>
  </div>

  <div class="add-form">
    <div class="title">Update Flight</div>
    <form method="post" action="{{ url_for('flight_blueprint.update_flight') }}">
        <div class="user-details">
            <div class="input-box">
                <span class="details">Flight Number</span>
                <input type="text" name = "idFlight" placeholder="Enter Flight Number" required>
            </div>
            <div class="input-box">
                <span class="details">New Destination</span>
                <input type="text" name = "newDestination" placeholder="Enter Destination">
            </div>
            <div class="input-box">
                <span class="details">New Plane ID</span>
                <input type="text" name = "newPlaneID" placeholder="Enter Plane ID">
            </div>
            <div class="input-box">
                <span class="details">New Departure Date</span>
                <input type="date" name = "newDepartureDate" placeholder="Enter Departure Date">
            </div>
            <div class="input-box">
                <span class="details">New Departure Time</span>
                <input type="time" name = "newDepartureTime" placeholder="Enter Departure Time">
            </div>
            <div class="input-box">
                <span class="details">New Flight Duration</span>
                <input type="number" name = "newFlightTime"placeholder="Flight Duration in minutes">
            </div>
        </div>
        <div class="button">
            <input type="Submit" value="Update">
        </div>
    </form>
  </div>

  <div class="add-form">
    <div class="title">Delete Scheduled Flight</div>
    <form method="post" action="{{ url_for('flight_blueprint.delete_flight') }}">
        <div class="user-details">
            <div class="input-box">
                <span class="details">Flight Number</span>
                <input type="text" name = "idFlight" placeholder="Enter Flight Number" required>
            </div>
            
        <div class="button">
            <input type="Submit" value="Delete">
        </div>
    </form>
  </div>

</div>

  </table>

  </body>
</html>

templates/Website/search_employee.html
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <title>Employee Search</title>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
  </head>

    <body class="home">
      <header class="header">
        <a href="#" class="logo">Airline DBMS</a>
        <nav class="navbar">
            <a href="add_employee.html">Add Employee</a>
            <a href="search_employee.html">Search Employee</a>
            <a href="schedule_flight.html">Flight Scheduler</a>
            <a href="create_department.html">Create Department</a>
            <a href="add_plane.html">Add Plane</a>
            <a href="advanced.html">Advanced</a>
        </nav>
      </header>


    <div class="all-forms">
      <div class="add-form">
        <h1 class="search-title">Employee Directory</h1>

        <form class="search-form" action = "{{ url_for('employee_blueprint.search_employee') }}" method = "post">
          <label for="search">Search for user:</label>
          <input id="search" type="text" name="employeeID" placeholder="Enter Employee ID...">

          <div class="button">
                <input type="submit" value="Submit">
          </div>
        </form>
  
        <h1 class="search-title">Department Directory</h1>
      
        <form class="search-form" action = "{{ url_for('department_blueprint.search_department') }}" method = "post">
          <label for="search">Search for department:</label>
          <input id="search" type="text" name="idDepartment" placeholder="Enter Department ID...">
          <div class="button">
            <input type="submit" value="Submit">
          </div>
        </form>


        
          <h1 class="search-title">Plane Directory</h1>
        <form class="search-form" action = "" method = "post">
          <label for="search">Search for plane:</label>
          <input id="search" type="text" name="usersearch" placeholder="Enter Plane ID">
          
          <div class="button">
            <input type="submit" value="Submit">
          </div>
        </form>
        
      </div>

        <div id="viewing-window">
          <h2>Employee</h2>
          <ul>
              {% if employee %}
                <li class = "flight">
                    Employee ID: {{ employee.idEmployee }}<br>
                    First Name: {{ employee.firstName }}<br>
                    Last Name: {{ employee.lastName }}<br>
                    Position: {{ employee.positionID }}<br>
                    Salary: {{ employee.salary }}<br>
                    Employment Status: {{ employee.status }}<br>
                </li>
              {% else %}
                  <p>No employee found</p>
              {% endif %}
          </ul>
      </div>
      </div>
    </div>
  </body>
</html>

templates/Website/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
</head>
<body>
    <h1>Search Results</h1>
    
    {% if search_result %}
        <p>Employee found:</p>
        <ul>
            <li>ID: {{ search_result.idEmployee }}</li>
            <li>First Name: {{ search_result.firstName }}</li>
            <li>Last Name: {{ search_result.lastName }}</li>
            <li>Position ID: {{ search_result.positionID }}</li>
            <li>Salary: {{ search_result.salary }}</li>
            <li>Status: {{ search_result.status }}</li>
        </ul>
    {% else %}
        <p>{{ error_message }}</p>
    {% endif %}


</body>
</html>